2024-09-27 17:56:37,596 INFO    Thread-10 (_run_job):62871 [wandb_setup.py:_flush():77] Current SDK version is 0.17.8
2024-09-27 17:56:37,596 INFO    Thread-10 (_run_job):62871 [wandb_setup.py:_flush():77] Configure stats pid to 62871
2024-09-27 17:56:37,596 INFO    Thread-10 (_run_job):62871 [wandb_setup.py:_flush():77] Loading settings from /Users/arnavkapur/.config/wandb/settings
2024-09-27 17:56:37,597 INFO    Thread-10 (_run_job):62871 [wandb_setup.py:_flush():77] Loading settings from /Users/arnavkapur/Desktop/Analysis_3DImagery/imagery2024/Generation/pytorch/wandb/settings
2024-09-27 17:56:37,597 INFO    Thread-10 (_run_job):62871 [wandb_setup.py:_flush():77] Loading settings from environment variables: {'project': 'EEGNet_P001_final', 'entity': 'constanzealbrecht-eth-z-rich', 'root_dir': '/Users/arnavkapur/Desktop/Analysis_3DImagery/imagery2024/Generation/pytorch', 'run_id': 'mxvh0fzl', 'sweep_param_path': '/Users/arnavkapur/Desktop/Analysis_3DImagery/imagery2024/Generation/pytorch/wandb/sweep-hk57ojfe/config-mxvh0fzl.yaml', 'sweep_id': 'hk57ojfe'}
2024-09-27 17:56:37,597 INFO    Thread-10 (_run_job):62871 [wandb_setup.py:_flush():77] Applying setup settings: {'_disable_service': False}
2024-09-27 17:56:37,597 INFO    Thread-10 (_run_job):62871 [wandb_setup.py:_flush():77] Inferring run settings from compute environment: {'program_relpath': 'Generation/pytorch/train.py', 'program_abspath': '/Users/arnavkapur/Desktop/Analysis_3DImagery/imagery2024/Generation/pytorch/train.py', 'program': '/Users/arnavkapur/Desktop/Analysis_3DImagery/imagery2024/Generation/pytorch/train.py'}
2024-09-27 17:56:37,597 INFO    Thread-10 (_run_job):62871 [wandb_init.py:_log_setup():524] Logging user logs to /Users/arnavkapur/Desktop/Analysis_3DImagery/imagery2024/Generation/pytorch/wandb/run-20240927_175637-mxvh0fzl/logs/debug.log
2024-09-27 17:56:37,597 INFO    Thread-10 (_run_job):62871 [wandb_init.py:_log_setup():525] Logging internal logs to /Users/arnavkapur/Desktop/Analysis_3DImagery/imagery2024/Generation/pytorch/wandb/run-20240927_175637-mxvh0fzl/logs/debug-internal.log
2024-09-27 17:56:37,597 INFO    Thread-10 (_run_job):62871 [wandb_init.py:init():607] calling init triggers
2024-09-27 17:56:37,597 INFO    Thread-10 (_run_job):62871 [wandb_init.py:init():614] wandb.init called with sweep_config: {'datamodule': {'batch_size': 128, 'data_dir': '/Users/arnavkapur/Desktop/Analysis_3DImagery/imagery2024/Generation/Segmented_data/train/P10train.npy', 'num_workers': 0, 'seed': 42, 'val_run': '/Users/arnavkapur/Desktop/Analysis_3DImagery/imagery2024/Generation/Segmented_data/val/P10val.npy'}, 'final_model': False, 'fine_tuning': False, 'model': {'D': 2, 'F1': 64, 'drop_prob': 0.5, 'final_conv_length': 'auto', 'in_chans': 64, 'input_window_samples': 4096, 'kernel_length': 64, 'lr': 0.0014320513763789317, 'momentum': 0.1, 'n_classes': 6, 'one_cycle_lr': True, 'pool_mode': 'max', 'weight_decay': 0.00974608042250015}, 'model_name': 'EEGNET', 'trainer': {'max_epochs': 30}}
config: {}
2024-09-27 17:56:37,598 INFO    Thread-10 (_run_job):62871 [wandb_init.py:init():652] wandb.init() called when a run is still active
2024-09-27 17:56:38,175 INFO    Thread-6 (_run_job):62871 [wandb_run.py:_restore():2406] restore
2024-09-27 17:56:38,175 INFO    Thread-6 (_run_job):62871 [wandb_run.py:_restore():2412] restore done
2024-09-27 17:56:38,175 ERROR   Thread-6 (_run_job):62871 [wandb_run.py:_atexit_cleanup():2445] Problem finishing run
Traceback (most recent call last):
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/agents/pyagent.py", line 306, in _run_job
    self._function()
  File "/Users/arnavkapur/Desktop/Analysis_3DImagery/imagery2024/Generation/pytorch/train.py", line 108, in main
    trainer.fit(model = model, datamodule = dm)
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 538, in fit
    call._call_and_handle_interrupt(
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 47, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 574, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 981, in _run
    results = self._run_stage()
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1023, in _run_stage
    self._run_sanity_check()
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1052, in _run_sanity_check
    val_loop.run()
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pytorch_lightning/loops/utilities.py", line 178, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 128, in run
    batch, batch_idx, dataloader_idx = next(data_fetcher)
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pytorch_lightning/loops/fetchers.py", line 133, in __next__
    batch = super().__next__()
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pytorch_lightning/loops/fetchers.py", line 60, in __next__
    batch = next(self.iterator)
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pytorch_lightning/utilities/combined_loader.py", line 341, in __next__
    out = next(self._iterator)
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pytorch_lightning/utilities/combined_loader.py", line 142, in __next__
    out = next(self.iterators[0])
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 675, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/Users/arnavkapur/Desktop/Analysis_3DImagery/imagery2024/Generation/pytorch/data_setup/Dataset.py", line 56, in __getitem__
    return self.data[idx], self.labels[idx]
IndexError: index 47 is out of bounds for dimension 0 with size 47

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2436, in _atexit_cleanup
    self._on_finish()
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2699, in _on_finish
    _ = exit_handle.wait(timeout=-1, on_progress=self._on_progress_exit)
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 298, in wait
    on_probe(probe_handle)
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2647, in _on_probe_exit
    result = handle.wait(timeout=0, release=False)
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 281, in wait
    raise MailboxError("transport failed")
wandb.sdk.lib.mailbox.MailboxError: transport failed
2024-09-27 17:56:38,464 ERROR   MainThread:62871 [pyagent.py:_run_jobs_from_queue():234] Run mxvh0fzl errored:
Traceback (most recent call last):
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/agents/pyagent.py", line 306, in _run_job
    self._function()
  File "/Users/arnavkapur/Desktop/Analysis_3DImagery/imagery2024/Generation/pytorch/train.py", line 108, in main
    trainer.fit(model = model, datamodule = dm)
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 538, in fit
    call._call_and_handle_interrupt(
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 47, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 574, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 964, in _run
    _log_hyperparams(self)
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pytorch_lightning/loggers/utilities.py", line 93, in _log_hyperparams
    logger.log_hyperparams(hparams_initial)
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/lightning_utilities/core/rank_zero.py", line 42, in wrapped_fn
    return fn(*args, **kwargs)
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pytorch_lightning/loggers/wandb.py", line 428, in log_hyperparams
    self.experiment.config.update(params, allow_val_change=True)
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 189, in update
    self._callback(data=sanitized)
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 413, in wrapper_fn
    raise errors.UsageError(resolved_message)
wandb.errors.UsageError: Run (3d1ij1jy) is finished. The call to `_config_callback` will be ignored. Please make sure that you are using an active run.

2024-09-27 17:56:44,815 INFO    Thread-12 (_run_job):62871 [wandb_setup.py:_flush():77] Current SDK version is 0.17.8
2024-09-27 17:56:44,815 INFO    Thread-12 (_run_job):62871 [wandb_setup.py:_flush():77] Configure stats pid to 62871
2024-09-27 17:56:44,815 INFO    Thread-12 (_run_job):62871 [wandb_setup.py:_flush():77] Loading settings from /Users/arnavkapur/.config/wandb/settings
2024-09-27 17:56:44,815 INFO    Thread-12 (_run_job):62871 [wandb_setup.py:_flush():77] Loading settings from /Users/arnavkapur/Desktop/Analysis_3DImagery/imagery2024/Generation/pytorch/wandb/settings
2024-09-27 17:56:44,815 INFO    Thread-12 (_run_job):62871 [wandb_setup.py:_flush():77] Loading settings from environment variables: {'project': 'EEGNet_P001_final', 'entity': 'constanzealbrecht-eth-z-rich', 'root_dir': '/Users/arnavkapur/Desktop/Analysis_3DImagery/imagery2024/Generation/pytorch', 'run_id': '6uckkj56', 'sweep_param_path': '/Users/arnavkapur/Desktop/Analysis_3DImagery/imagery2024/Generation/pytorch/wandb/sweep-hk57ojfe/config-6uckkj56.yaml', 'sweep_id': 'hk57ojfe'}
2024-09-27 17:56:44,816 INFO    Thread-12 (_run_job):62871 [wandb_setup.py:_flush():77] Applying setup settings: {'_disable_service': False}
2024-09-27 17:56:44,816 INFO    Thread-12 (_run_job):62871 [wandb_setup.py:_flush():77] Inferring run settings from compute environment: {'program_relpath': 'Generation/pytorch/train.py', 'program_abspath': '/Users/arnavkapur/Desktop/Analysis_3DImagery/imagery2024/Generation/pytorch/train.py', 'program': '/Users/arnavkapur/Desktop/Analysis_3DImagery/imagery2024/Generation/pytorch/train.py'}
2024-09-27 17:56:44,816 INFO    Thread-12 (_run_job):62871 [wandb_setup.py:_flush():77] Applying login settings: {}
2024-09-27 17:56:44,816 INFO    Thread-12 (_run_job):62871 [wandb_init.py:_log_setup():524] Logging user logs to /Users/arnavkapur/Desktop/Analysis_3DImagery/imagery2024/Generation/pytorch/wandb/run-20240927_175644-6uckkj56/logs/debug.log
2024-09-27 17:56:44,816 INFO    Thread-12 (_run_job):62871 [wandb_init.py:_log_setup():525] Logging internal logs to /Users/arnavkapur/Desktop/Analysis_3DImagery/imagery2024/Generation/pytorch/wandb/run-20240927_175644-6uckkj56/logs/debug-internal.log
2024-09-27 17:56:44,817 INFO    Thread-12 (_run_job):62871 [wandb_init.py:init():607] calling init triggers
2024-09-27 17:56:44,817 INFO    Thread-12 (_run_job):62871 [wandb_init.py:init():614] wandb.init called with sweep_config: {'datamodule': {'batch_size': 64, 'data_dir': '/Users/arnavkapur/Desktop/Analysis_3DImagery/imagery2024/Generation/Segmented_data/train/P10train.npy', 'num_workers': 0, 'seed': 42, 'val_run': '/Users/arnavkapur/Desktop/Analysis_3DImagery/imagery2024/Generation/Segmented_data/val/P10val.npy'}, 'final_model': False, 'fine_tuning': False, 'model': {'D': 2, 'F1': 16, 'drop_prob': 0.5, 'final_conv_length': 'auto', 'in_chans': 64, 'input_window_samples': 4096, 'kernel_length': 64, 'lr': 0.0015949204088470338, 'momentum': 0.1, 'n_classes': 6, 'one_cycle_lr': True, 'pool_mode': 'max', 'weight_decay': 0.0020710960273095883}, 'model_name': 'EEGNET', 'trainer': {'max_epochs': 30}}
config: {}
2024-09-27 17:56:44,817 INFO    Thread-12 (_run_job):62871 [wandb_init.py:init():657] starting backend
2024-09-27 17:56:44,817 INFO    Thread-12 (_run_job):62871 [wandb_init.py:init():661] setting up manager
2024-09-27 17:56:44,825 INFO    Thread-12 (_run_job):62871 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-09-27 17:56:44,825 INFO    Thread-12 (_run_job):62871 [wandb_init.py:init():669] backend started and connected
2024-09-27 17:56:44,840 INFO    Thread-12 (_run_job):62871 [wandb_run.py:_config_callback():1392] config_cb None None {'datamodule': {'batch_size': 64, 'data_dir': '/Users/arnavkapur/Desktop/Analysis_3DImagery/imagery2024/Generation/Segmented_data/train/P10train.npy', 'num_workers': 0, 'seed': 42, 'val_run': '/Users/arnavkapur/Desktop/Analysis_3DImagery/imagery2024/Generation/Segmented_data/val/P10val.npy'}, 'final_model': False, 'fine_tuning': False, 'model': {'D': 2, 'F1': 16, 'drop_prob': 0.5, 'final_conv_length': 'auto', 'in_chans': 64, 'input_window_samples': 4096, 'kernel_length': 64, 'lr': 0.0015949204088470338, 'momentum': 0.1, 'n_classes': 6, 'one_cycle_lr': True, 'pool_mode': 'max', 'weight_decay': 0.0020710960273095883}, 'model_name': 'EEGNET', 'trainer': {'max_epochs': 30}}
2024-09-27 17:56:44,843 INFO    Thread-12 (_run_job):62871 [wandb_init.py:init():767] updated telemetry
2024-09-27 17:56:44,882 INFO    Thread-12 (_run_job):62871 [wandb_init.py:init():800] communicating run to backend with 90.0 second timeout
2024-09-27 17:56:45,101 INFO    Thread-12 (_run_job):62871 [wandb_init.py:init():851] starting run threads in backend
2024-09-27 17:56:45,510 INFO    Thread-12 (_run_job):62871 [wandb_run.py:_console_start():2463] atexit reg
2024-09-27 17:56:45,511 INFO    Thread-12 (_run_job):62871 [wandb_run.py:_redirect():2309] redirect: wrap_raw
2024-09-27 17:56:45,511 INFO    Thread-12 (_run_job):62871 [wandb_run.py:_redirect():2374] Wrapping output streams.
2024-09-27 17:56:45,514 INFO    Thread-12 (_run_job):62871 [wandb_run.py:_redirect():2399] Redirects installed.
2024-09-27 17:56:45,515 INFO    Thread-12 (_run_job):62871 [wandb_init.py:init():894] run started, returning control to user process
2024-09-27 17:56:46,177 INFO    Thread-12 (_run_job):62871 [wandb_run.py:_config_callback():1392] config_cb None None {'lr': 0.0015949204088470338, 'one_cycle_lr': True, 'weight_decay': 0.0020710960273095883, 'epochs': 30, 'in_chans': 64, 'n_classes': 6, 'final_conv_length': 'auto', 'input_window_samples': 4096, 'F1': 16, 'D': 2, 'kernel_length': 64, 'pool_mode': 'max', 'drop_prob': 0.5, 'momentum': 0.1}
2024-09-27 17:56:46,186 INFO    Thread-12 (_run_job):62871 [wandb_run.py:_finish():2160] finishing run constanzealbrecht-eth-z-rich/EEGNet_P001_final/6uckkj56
2024-09-27 17:56:46,186 INFO    Thread-12 (_run_job):62871 [wandb_run.py:_atexit_cleanup():2424] got exitcode: 1
2024-09-27 17:56:46,186 INFO    Thread-12 (_run_job):62871 [wandb_run.py:_restore():2406] restore
2024-09-27 17:56:46,186 INFO    Thread-12 (_run_job):62871 [wandb_run.py:_restore():2412] restore done
2024-09-27 17:56:46,186 INFO    Thread-12 (_run_job):62871 [wandb_run.py:_on_finish():2677] communicating current version
2024-09-27 17:56:46,247 INFO    Thread-12 (_run_job):62871 [wandb_run.py:_on_finish():2686] got version response upgrade_message: "wandb version 0.18.2 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2024-09-27 17:56:49,789 INFO    Thread-12 (_run_job):62871 [wandb_run.py:_footer_history_summary_info():4078] rendering history
2024-09-27 17:56:49,789 INFO    Thread-12 (_run_job):62871 [wandb_run.py:_footer_history_summary_info():4110] rendering summary
2024-09-27 17:56:49,798 INFO    Thread-12 (_run_job):62871 [wandb_run.py:_footer_sync_info():4037] logging synced files
2024-09-27 17:56:49,800 ERROR   MainThread:62871 [pyagent.py:_run_jobs_from_queue():234] Run 6uckkj56 errored:
Traceback (most recent call last):
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/agents/pyagent.py", line 306, in _run_job
    self._function()
  File "/Users/arnavkapur/Desktop/Analysis_3DImagery/imagery2024/Generation/pytorch/train.py", line 108, in main
    trainer.fit(model = model, datamodule = dm)
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 538, in fit
    call._call_and_handle_interrupt(
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 47, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 574, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 981, in _run
    results = self._run_stage()
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1023, in _run_stage
    self._run_sanity_check()
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1052, in _run_sanity_check
    val_loop.run()
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pytorch_lightning/loops/utilities.py", line 178, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 128, in run
    batch, batch_idx, dataloader_idx = next(data_fetcher)
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pytorch_lightning/loops/fetchers.py", line 133, in __next__
    batch = super().__next__()
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pytorch_lightning/loops/fetchers.py", line 60, in __next__
    batch = next(self.iterator)
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pytorch_lightning/utilities/combined_loader.py", line 341, in __next__
    out = next(self._iterator)
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pytorch_lightning/utilities/combined_loader.py", line 142, in __next__
    out = next(self.iterators[0])
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 675, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/Users/arnavkapur/Desktop/Analysis_3DImagery/imagery2024/Generation/pytorch/data_setup/Dataset.py", line 56, in __getitem__
    return self.data[idx], self.labels[idx]
IndexError: index 47 is out of bounds for dimension 0 with size 47

2024-09-27 17:56:55,734 INFO    Thread-15 (_run_job):62871 [wandb_setup.py:_flush():77] Current SDK version is 0.17.8
2024-09-27 17:56:55,734 INFO    Thread-15 (_run_job):62871 [wandb_setup.py:_flush():77] Configure stats pid to 62871
2024-09-27 17:56:55,734 INFO    Thread-15 (_run_job):62871 [wandb_setup.py:_flush():77] Loading settings from /Users/arnavkapur/.config/wandb/settings
2024-09-27 17:56:55,734 INFO    Thread-15 (_run_job):62871 [wandb_setup.py:_flush():77] Loading settings from /Users/arnavkapur/Desktop/Analysis_3DImagery/imagery2024/Generation/pytorch/wandb/settings
2024-09-27 17:56:55,734 INFO    Thread-15 (_run_job):62871 [wandb_setup.py:_flush():77] Loading settings from environment variables: {'project': 'EEGNet_P001_final', 'entity': 'constanzealbrecht-eth-z-rich', 'root_dir': '/Users/arnavkapur/Desktop/Analysis_3DImagery/imagery2024/Generation/pytorch', 'run_id': 'q9m77xx0', 'sweep_param_path': '/Users/arnavkapur/Desktop/Analysis_3DImagery/imagery2024/Generation/pytorch/wandb/sweep-hk57ojfe/config-q9m77xx0.yaml', 'sweep_id': 'hk57ojfe'}
2024-09-27 17:56:55,734 INFO    Thread-15 (_run_job):62871 [wandb_setup.py:_flush():77] Applying setup settings: {'_disable_service': False}
2024-09-27 17:56:55,734 INFO    Thread-15 (_run_job):62871 [wandb_setup.py:_flush():77] Inferring run settings from compute environment: {'program_relpath': 'Generation/pytorch/train.py', 'program_abspath': '/Users/arnavkapur/Desktop/Analysis_3DImagery/imagery2024/Generation/pytorch/train.py', 'program': '/Users/arnavkapur/Desktop/Analysis_3DImagery/imagery2024/Generation/pytorch/train.py'}
2024-09-27 17:56:55,735 INFO    Thread-15 (_run_job):62871 [wandb_setup.py:_flush():77] Applying login settings: {}
2024-09-27 17:56:55,735 INFO    Thread-15 (_run_job):62871 [wandb_init.py:_log_setup():524] Logging user logs to /Users/arnavkapur/Desktop/Analysis_3DImagery/imagery2024/Generation/pytorch/wandb/run-20240927_175655-q9m77xx0/logs/debug.log
2024-09-27 17:56:55,735 INFO    Thread-15 (_run_job):62871 [wandb_init.py:_log_setup():525] Logging internal logs to /Users/arnavkapur/Desktop/Analysis_3DImagery/imagery2024/Generation/pytorch/wandb/run-20240927_175655-q9m77xx0/logs/debug-internal.log
2024-09-27 17:56:55,735 INFO    Thread-15 (_run_job):62871 [wandb_init.py:init():607] calling init triggers
2024-09-27 17:56:55,735 INFO    Thread-15 (_run_job):62871 [wandb_init.py:init():614] wandb.init called with sweep_config: {'datamodule': {'batch_size': 128, 'data_dir': '/Users/arnavkapur/Desktop/Analysis_3DImagery/imagery2024/Generation/Segmented_data/train/P10train.npy', 'num_workers': 0, 'seed': 42, 'val_run': '/Users/arnavkapur/Desktop/Analysis_3DImagery/imagery2024/Generation/Segmented_data/val/P10val.npy'}, 'final_model': False, 'fine_tuning': False, 'model': {'D': 2, 'F1': 64, 'drop_prob': 0.25, 'final_conv_length': 'auto', 'in_chans': 64, 'input_window_samples': 4096, 'kernel_length': 64, 'lr': 0.0022972252212887967, 'momentum': 0.1, 'n_classes': 6, 'one_cycle_lr': True, 'pool_mode': 'max', 'weight_decay': 0.007681825909875838}, 'model_name': 'EEGNET', 'trainer': {'max_epochs': 30}}
config: {}
2024-09-27 17:56:55,735 INFO    Thread-15 (_run_job):62871 [wandb_init.py:init():657] starting backend
2024-09-27 17:56:55,735 INFO    Thread-15 (_run_job):62871 [wandb_init.py:init():661] setting up manager
2024-09-27 17:56:55,742 INFO    Thread-15 (_run_job):62871 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-09-27 17:56:55,742 INFO    Thread-15 (_run_job):62871 [wandb_init.py:init():669] backend started and connected
2024-09-27 17:56:55,756 INFO    Thread-15 (_run_job):62871 [wandb_run.py:_config_callback():1392] config_cb None None {'datamodule': {'batch_size': 128, 'data_dir': '/Users/arnavkapur/Desktop/Analysis_3DImagery/imagery2024/Generation/Segmented_data/train/P10train.npy', 'num_workers': 0, 'seed': 42, 'val_run': '/Users/arnavkapur/Desktop/Analysis_3DImagery/imagery2024/Generation/Segmented_data/val/P10val.npy'}, 'final_model': False, 'fine_tuning': False, 'model': {'D': 2, 'F1': 64, 'drop_prob': 0.25, 'final_conv_length': 'auto', 'in_chans': 64, 'input_window_samples': 4096, 'kernel_length': 64, 'lr': 0.0022972252212887967, 'momentum': 0.1, 'n_classes': 6, 'one_cycle_lr': True, 'pool_mode': 'max', 'weight_decay': 0.007681825909875838}, 'model_name': 'EEGNET', 'trainer': {'max_epochs': 30}}
2024-09-27 17:56:55,759 INFO    Thread-15 (_run_job):62871 [wandb_init.py:init():767] updated telemetry
2024-09-27 17:56:55,796 INFO    Thread-15 (_run_job):62871 [wandb_init.py:init():800] communicating run to backend with 90.0 second timeout
2024-09-27 17:56:55,996 INFO    Thread-15 (_run_job):62871 [wandb_init.py:init():851] starting run threads in backend
2024-09-27 17:56:56,433 INFO    Thread-15 (_run_job):62871 [wandb_run.py:_console_start():2463] atexit reg
2024-09-27 17:56:56,433 INFO    Thread-15 (_run_job):62871 [wandb_run.py:_redirect():2309] redirect: wrap_raw
2024-09-27 17:56:56,433 INFO    Thread-15 (_run_job):62871 [wandb_run.py:_redirect():2374] Wrapping output streams.
2024-09-27 17:56:56,434 INFO    Thread-15 (_run_job):62871 [wandb_run.py:_redirect():2399] Redirects installed.
2024-09-27 17:56:56,435 INFO    Thread-15 (_run_job):62871 [wandb_init.py:init():894] run started, returning control to user process
2024-09-27 17:56:58,318 INFO    Thread-15 (_run_job):62871 [wandb_run.py:_config_callback():1392] config_cb None None {'lr': 0.0022972252212887967, 'one_cycle_lr': True, 'weight_decay': 0.007681825909875838, 'epochs': 30, 'in_chans': 64, 'n_classes': 6, 'final_conv_length': 'auto', 'input_window_samples': 4096, 'F1': 64, 'D': 2, 'kernel_length': 64, 'pool_mode': 'max', 'drop_prob': 0.25, 'momentum': 0.1}
2024-09-27 17:56:58,331 INFO    Thread-15 (_run_job):62871 [wandb_run.py:_finish():2160] finishing run constanzealbrecht-eth-z-rich/EEGNet_P001_final/q9m77xx0
2024-09-27 17:56:58,331 INFO    Thread-15 (_run_job):62871 [wandb_run.py:_atexit_cleanup():2424] got exitcode: 1
2024-09-27 17:56:58,331 INFO    Thread-15 (_run_job):62871 [wandb_run.py:_restore():2406] restore
2024-09-27 17:56:58,332 INFO    Thread-15 (_run_job):62871 [wandb_run.py:_restore():2412] restore done
2024-09-27 17:56:58,332 INFO    Thread-15 (_run_job):62871 [wandb_run.py:_on_finish():2677] communicating current version
2024-09-27 17:56:58,399 INFO    Thread-15 (_run_job):62871 [wandb_run.py:_on_finish():2686] got version response upgrade_message: "wandb version 0.18.2 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2024-09-27 17:57:02,715 INFO    Thread-15 (_run_job):62871 [wandb_run.py:_footer_history_summary_info():4078] rendering history
2024-09-27 17:57:02,715 INFO    Thread-15 (_run_job):62871 [wandb_run.py:_footer_history_summary_info():4110] rendering summary
2024-09-27 17:57:02,723 INFO    Thread-15 (_run_job):62871 [wandb_run.py:_footer_sync_info():4037] logging synced files
2024-09-27 17:57:02,725 ERROR   MainThread:62871 [pyagent.py:_run_jobs_from_queue():234] Run q9m77xx0 errored:
Traceback (most recent call last):
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/wandb/agents/pyagent.py", line 306, in _run_job
    self._function()
  File "/Users/arnavkapur/Desktop/Analysis_3DImagery/imagery2024/Generation/pytorch/train.py", line 108, in main
    trainer.fit(model = model, datamodule = dm)
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 538, in fit
    call._call_and_handle_interrupt(
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 47, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 574, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 981, in _run
    results = self._run_stage()
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1023, in _run_stage
    self._run_sanity_check()
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1052, in _run_sanity_check
    val_loop.run()
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pytorch_lightning/loops/utilities.py", line 178, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 128, in run
    batch, batch_idx, dataloader_idx = next(data_fetcher)
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pytorch_lightning/loops/fetchers.py", line 133, in __next__
    batch = super().__next__()
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pytorch_lightning/loops/fetchers.py", line 60, in __next__
    batch = next(self.iterator)
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pytorch_lightning/utilities/combined_loader.py", line 341, in __next__
    out = next(self._iterator)
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pytorch_lightning/utilities/combined_loader.py", line 142, in __next__
    out = next(self.iterators[0])
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 675, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/Users/arnavkapur/.pyenv/versions/3.10.12/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/Users/arnavkapur/Desktop/Analysis_3DImagery/imagery2024/Generation/pytorch/data_setup/Dataset.py", line 56, in __getitem__
    return self.data[idx], self.labels[idx]
IndexError: index 47 is out of bounds for dimension 0 with size 47

2024-09-27 17:57:02,726 ERROR   MainThread:62871 [pyagent.py:_run_jobs_from_queue():245] Detected 3 failed runs in the first 60 seconds, killing sweep.
